spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teammanagement
    username: tm
    password: tm
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logo-search:
  google-api-key: ${GOOGLE_API_KEY:}
  google-cse-id: ${GOOGLE_CSE_ID:}

server:
  servlet:
    session:
      timeout: 1h

app:
  admin:
    email: ${ADMIN_EMAIL:}
    password: ${ADMIN_PASSWORD:}
